### ISSUE TITLE
How to add any other animations to this Toast

### ISSUE THREAD

**Issue by logeshpalani33** [andrius-k/Toast#11]
Am trying to add new animation to this view, there is no set properties or methods

or else 

Add new animations properties

**Comment by andrius-k** [comment]
Hi, 
Sorry it took a while to respond! You can create a new `ToastAnimator` and define a custom animation in there. Take a look at one of the default ones: https://github.com/andrius-k/Toast/blob/master/Toast/Animation/ScaleAnimator.cs

After creating an animator you can use it like this:
``` cs
Toast.MakeToast("This is a message")
     .SetAnimator(new YournewAnimator())
     .Show();
```

Please let me know if this helps!
