### ISSUE TITLE
Add ToastPosition.Center

### ISSUE THREAD

**Issue by Seuleuzeuh** [andrius-k/Toast#2]
Hi,
First, you've made a great work on this plugin !

It's will be even greater if you can add ToastPosition.Center.

Thanks a lot.

**Comment by andrius-k** [comment]
Hi,

thanks. I was thinking about this myself and now added this ability. There is `ToastPosition.Center`. I will soon upload updated version of the package to nuget.org.

Regards

**Comment by andrius-k** [comment]
Hi,

updated nuget package is already available.

Regards
