### ISSUE TITLE
Question: How to force dismiss a toast?

### ISSUE THREAD

**Issue by Stensan** [andrius-k/Toast#4]
Hi, I use SetAutoDismiss(true) so calling Dismiss(); method has no effect. But sometimes I want to show a second toast while the first one is still visible. The second toast will be on top of the other one and that doesn't look great. How do I force dismiss a toast, before showing another?

**Comment by andrius-k** [comment]
Hi Stensan,

Currently there is no way to dismiss auto-dismissable toast. But I'm planning to make an update where this exact functionality will be enabled because, really, there is no reason why calling `Dismiss()` shouldn't dismiss an auto-dismissable toast as well. So stay tuned!

**Comment by Stensan** [comment]
Cool, thanks! :)

**Comment by andrius-k** [comment]
Hi Stensan,

I uploaded a new version of the package to nuget.org. Now calling `Dismiss()` will dismiss both auto-dismissible and non-auto-dismissible toasts.

Chears ;)
