### ISSUE TITLE
Customisable toast title location

### ISSUE THREAD

**Issue by katkusmt** [andrius-k/Toast#5]
Hey,

Really like your plugin, the customisation and all.

Would it be possible to move the title to the left and the text to the right? Something like: 
![image](https://user-images.githubusercontent.com/17209970/44774779-a35ee600-ab7c-11e8-922b-4112576cc3a9.png)

Setting the title to a flaticon/fontawesome or any icon and setting the font lets me add an icon, but I want it on the left. Is this already possible or still needs to be implemented? Is this achievable with the custom view?

**Comment by andrius-k** [comment]
Hi,

I'm glad you like this plugin!

Unfortunately there is no way to achieve this using current views. So in order to get the layout that you want you would have to write a custom view. There is a tutorial on how to do that in [readme](https://github.com/andrius-k/Toast/#writing-custom-views)
